package com.earthcrying.entity;

public enum ImpactCategory {
    DIGITAL_CARBON_FOOTPRINT,
    TIRE_BRAKE_DUST,
    FAST_FASHION_MICROPLASTICS,
    LIGHT_POLLUTION,
    UNDERWATER_NOISE_POLLUTION,
    FERTILIZER_RUNOFF,
    E_WASTE_RARE_EARTH_MINING,
    HIDDEN_WATER_FOOTPRINT,
    PALM_OIL_SUPPLY_CHAINS,
    SPACE_DEBRIS_SATELLITE_POLLUTION,
    SOIL_EROSION_MONOCULTURE,
    INDOOR_VOCS_FRAGRANCE_CHEMICALS
}